<template>
    <div class="loadingio-spinner-spin-ouv60kquwg">
        <div class="ldio-kei0fx234in">
            <div v-for="item in 9" :key="item">
                <div></div>
            </div>
        </div>
    </div>
</template>
<style type="text/css">
@keyframes ldio-kei0fx234in {
    0% {
        opacity: 1;
        backface-visibility: hidden;
        transform: translateZ(0) scale(1.5, 1.5);
    }
    100% {
        opacity: 0;
        backface-visibility: hidden;
        transform: translateZ(0) scale(1, 1);
    }
}
.ldio-kei0fx234in div > div {
    position: absolute;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: var(--gradient);
    animation: ldio-kei0fx234in 1s linear infinite;
}
.ldio-kei0fx234in div:nth-child(1) > div {
    left: 74px;
    top: 44px;
    animation-delay: -0.8888888888888888s;
}
.ldio-kei0fx234in > div:nth-child(1) {
    transform: rotate(0deg);
    transform-origin: 80px 50px;
}
.ldio-kei0fx234in div:nth-child(2) > div {
    left: 67px;
    top: 63px;
    animation-delay: -0.7777777777777778s;
}
.ldio-kei0fx234in > div:nth-child(2) {
    transform: rotate(40deg);
    transform-origin: 73px 69px;
}
.ldio-kei0fx234in div:nth-child(3) > div {
    left: 49px;
    top: 74px;
    animation-delay: -0.6666666666666666s;
}
.ldio-kei0fx234in > div:nth-child(3) {
    transform: rotate(80deg);
    transform-origin: 55px 80px;
}
.ldio-kei0fx234in div:nth-child(4) > div {
    left: 29px;
    top: 70px;
    animation-delay: -0.5555555555555556s;
}
.ldio-kei0fx234in > div:nth-child(4) {
    transform: rotate(120deg);
    transform-origin: 35px 76px;
}
.ldio-kei0fx234in div:nth-child(5) > div {
    left: 16px;
    top: 54px;
    animation-delay: -0.4444444444444444s;
}
.ldio-kei0fx234in > div:nth-child(5) {
    transform: rotate(160deg);
    transform-origin: 22px 60px;
}
.ldio-kei0fx234in div:nth-child(6) > div {
    left: 16px;
    top: 34px;
    animation-delay: -0.3333333333333333s;
}
.ldio-kei0fx234in > div:nth-child(6) {
    transform: rotate(200deg);
    transform-origin: 22px 40px;
}
.ldio-kei0fx234in div:nth-child(7) > div {
    left: 29px;
    top: 18px;
    animation-delay: -0.2222222222222222s;
}
.ldio-kei0fx234in > div:nth-child(7) {
    transform: rotate(240deg);
    transform-origin: 35px 24px;
}
.ldio-kei0fx234in div:nth-child(8) > div {
    left: 49px;
    top: 14px;
    animation-delay: -0.1111111111111111s;
}
.ldio-kei0fx234in > div:nth-child(8) {
    transform: rotate(280deg);
    transform-origin: 55px 20px;
}
.ldio-kei0fx234in div:nth-child(9) > div {
    left: 67px;
    top: 25px;
    animation-delay: 0s;
}
.ldio-kei0fx234in > div:nth-child(9) {
    transform: rotate(320deg);
    transform-origin: 73px 31px;
}
.loadingio-spinner-spin-ouv60kquwg {
    width: 24px;
    height: 24px;
    min-width: 24px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
}
.ldio-kei0fx234in {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.24);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-kei0fx234in div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
